classes:

  background:
    niceness: 19
    iosched_class: idle
    cgroup: cpu80

  game:
    niceness: -5
    iosched_class: best-effort

  heavy_cpu:
    niceness: 19
    iosched_class: best-effort
    cgroup: cpu90

  media:
    niceness: -3
    iosched_class: realtime

  oom_kill_first:
    oom_score_adj: 1000
  
  oom_kill_last:
    oom_score_adj: -1000

  realtime:
    niceness: -10
    iosched_class: realtime

  viewer:
    niceness: -3

  voip:
    niceness: -1
    iosched_class: best-effort
    iosched_priority: 7

cgroups: {}